### ISSUE TITLE
insight.phar is not publicly accessible after release

### ISSUE THREAD

**Issue by tareqas** [symfonycorp/insight#112]
The `insight.phar` uploaded to S3 in the release workflow isn’t publicly accessible. The current command:
```yaml
- name: Release
  run: |
      aws s3 cp build/insight.phar s3://get.insight.symfony.com/insight.phar
```
Adding `--acl public-read` might fix the problem.
